This script is used to generate prediction given a timeseries or filtered the prediction and save the result on a file.
Computing the prediction or filtering it with DTW is time consuming. Instead of computing it each time, just one time.

In [1]:
# packages
import pandas as pd
import numpy as np
import math
import pickle
from sklearn.cluster import DBSCAN
from scipy.cluster.hierarchy import fcluster, linkage
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from dtaidistance import dtw,similarity
from scipy.stats import pearsonr
from sklearn.model_selection import ParameterGrid

from claspy.segmentation import BinaryClaSPSegmentation

import ruptures as rpt

import stumpy
from aeon.segmentation import find_dominant_window_sizes

from aeon.segmentation import GreedyGaussianSegmenter

from aeon.segmentation import InformationGainSegmenter

from aeon.anomaly_detection import STRAY

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, make_scorer,mean_squared_error
from ruptures.metrics import precision_recall
import matplotlib.pyplot as plt
#from aeon.visualisation import plot_series_with_change_points, plot_series_with_profiles
import seaborn as sns

sns.set_theme()
sns.set_color_codes()

from claspy.tests.evaluation import f_measure,covering

from claspy.window_size import dominant_fourier_frequency, highest_autocorrelation, suss

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aeon\base\__init__.py:24: FutureWarning: The aeon package will soon be releasing v1.0.0 with the removal of legacy modules and interfaces such as BaseTransformer and BaseForecaster. This will contain breaking changes. See aeon-toolkit.org for more information. Set aeon.AEON_DEPRECATION_WARNING or the AEON_DEPRECATION_WARNING environmental variable to 'False' to disable this warning.
  warnings.warn(


Extracted features. Use the index of this list to use with iloc[]
<ol start="0">
  <li>Kinetic Global</li>
  <li>Kinetic Chest</li>
  <li>Directness Head</li>
  <li>Density</li>
  <li>left wrist ke</li>
  <li>right wrist ke</li>
  <li>left ankle ke</li>
  <li>right ankle ke</li>
  <li>head ke</li>
  <li>crouch density</li>
  <li>left leg density</li>
  <li>right leg density</li>
  <li>left hand density</li>
  <li>right hand density</li>
  <li>head density</li>
  <li>arto inferiore</li>
  <li>gamba</li>
  <li>coscia</li>
  <li>coscia dx</li>
  <li>coscia sx</li>
  <li>gamba sx</li>
  <li>gamba dx</li>
  <li>braccio sx</li>
  <li>braccio dx</li>
  <li>avambraccio sx</li>
  <li>avambraccio dx</li>
  <li>ARIEL speed magnitude</li>
  <li>ARIEL speed X component</li>
  <li>ARIEL speed Y component</li>
  <li>ARIEL speed Z component</li>
  <li>ARIEL acceleration magnitude</li>
  <li>ARIEL acceleration X component</li>
  <li>ARIEL acceleration Y component</li>
  <li>ARIEL acceleration Z component</li>
  <li>ARIEL jerk magnitude</li>
  <li>ARIEL jerk X component</li>
  <li>ARIEL jerk Y component</li>
  <li>ARIEL jerk Z component</li>
  <li>STRN speed magnitude</li>
  <li>STRN speed X component</li>
  <li>STRN speed Y component</li>
  <li>STRN speed Z component</li>
  <li>STRN acceleration magnitude</li>
  <li>STRN acceleration X component</li>
  <li>STRN acceleration Y component</li>
  <li>STRN accelerationZ component</li>
  <li>STRN jerk magnitude</li>
  <li>STRN jerk X component</li>
  <li>STRN jerk Y component</li>
  <li>STRN jerk Z component</li>
  <li>RHEL speed magnitude</li>
  <li>RHEL speed X component</li>
  <li>RHEL speed Y component</li>
  <li>RHEL speed Z component</li>
  <li>RHEL acceleration magnitude</li>
  <li>RHEL acceleration X component</li>
  <li>RHEL acceleration Y component</li>
  <li>RHEL acceleration Z component</li>
  <li>RHEL jerk magnitude</li>
  <li>RHEL jerk X component</li>
  <li>RHEL jerk Y component</li>
  <li>RHEL jerk Z component</li>
  <li>LHEL speed magnitude</li>
  <li>LHEL speed X component</li>
  <li>LHEL speed Y component</li>
  <li>LHEL speed Z component</li>
  <li>LHEL acceleration magnitude</li>
  <li>LHEL acceleration X component</li>
  <li>LHEL acceleration Y component</li>
  <li>LHEL acceleration Z component</li>
  <li>LHEL jerk magnitude</li>
  <li>LHEL jerk X component</li>
  <li>LHEL jerk Y component</li>
  <li>LHEL jerk Z component</li>
  <li>RPLM speed magnitude</li>
  <li>RPLM speed X component</li>
  <li>RPLM speed Y component</li>
  <li>RPLM speed Z component</li>
  <li>RPLM acceleration magnitude</li>
  <li>RPLM acceleration X component</li>
  <li>RPLM acceleration Y component</li>
  <li>RPLM acceleration Z component</li>
  <li>RPLM jerk magnitude</li>
  <li>RPLM jerk X component</li>
  <li>RPLM jerk Y component</li>
  <li>RPLM jerk Z component</li>
  <li>LPLM speed magnitude</li>
  <li>LPLM speed X component</li>
  <li>LPLM speed Y component</li>
  <li>LPLM speed Z component</li>
  <li>LPLM acceleration magnitude</li>
  <li>LPLM acceleration X component</li>
  <li>LPLM acceleration Y component</li>
  <li>LPLM acceleration Z component</li>
  <li>LPLM jerk magnitude</li>
  <li>LPLM jerk X component</li>
  <li>LPLM jerk Y component</li>
  <li>LPLM jerk Z component</li>




</ol>

In [2]:
# list of features. To access its name or its value while using iloc
features_name=[
    "kinetic_global",
    "kinetic_chest",
    "directness_head",
    "density",
    "left_wrist_ke",
    "right_wrist_ke",
    "left_ankle_ke",
    "right_ankle_ke",
    "head_ke",
    "crouch_density",
    "left_leg_density",
    "right_leg_density",
    "left_hand_density",
    "right_hand_density",
    "head_density",
    "arto_inferiore",
    "gamba",
    "coscia",
    "coscia_dx",
    "coscia_sx",
    "gamba_sx",
    "gamba_dx",
    "braccio_sx",
    "braccio_dx",
    "avambraccio_sx",
    "avambraccio_dx",
    "ARIEL_speed_magnitude",
    "ARIEL_speed_X_component",
    "ARIEL_speed_Y_component",
    "ARIEL_speed_Z_component",
    "ARIEL_acceleration_magnitude",
    "ARIEL_acceleration_X_component",
    "ARIEL_acceleration_Y_component",
    "ARIEL_acceleration_Z_component",
    "ARIEL_jerk_magnitude",
    "ARIEL_jerk_X_component",
    "ARIEL_jerk_Y_component",
    "ARIEL_jerk_Z_component",
    "STRN_speed_magnitude",
    "STRN_speed_X_component",
    "STRN_speed_Y_component",
    "STRN_speed_Z_component",
    "STRN_acceleration_magnitude",
    "STRN_acceleration_X_component",
    "STRN_acceleration_Y_component",
    "STRN_acceleration_Z_component",
    "STRN_jerk_magnitude",
    "STRN_jerk_X_component",
    "STRN_jerk_Y_component",
    "STRN_jerk_Z_component",
    "RHEL_speed_magnitude",
    "RHEL_speed_X_component",
    "RHEL_speed_Y_component",
    "RHEL_speed_Z_component",
    "RHEL_acceleration_magnitude",
    "RHEL_acceleration_X_component",
    "RHEL_acceleration_Y_component",
    "RHEL_acceleration_Z_component",
    "RHEL_jerk_magnitude",
    "RHEL_jerk_X_component",
    "RHEL_jerk_Y_component",
    "RHEL_jerk_Z_component",
    "LHEL_speed_magnitude",
    "LHEL_speed_X_component",
    "LHEL_speed_Y_component",
    "LHEL_speed_Z_component",
    "LHEL_acceleration_magnitude",
    "LHEL_acceleration_X_component",
    "LHEL_acceleration_Y_component",
    "LHEL_acceleration_Z_component",
    "LHEL_jerk_magnitude",
    "LHEL_jerk_X_component",
    "LHEL_jerk_Y_component",
    "LHEL_jerk_Z_component",
    "RPLM_speed_magnitude",
    "RPLM_speed_X_component",
    "RPLM_speed_Y_component",
    "RPLM_speed_Z_component",
    "RPLM_acceleration_magnitude",
    "RPLM_acceleration_X_component",
    "RPLM_acceleration_Y_component",
    "RPLM_acceleration_Z_component",
    "RPLM_jerk_magnitude",
    "RPLM_jerk_X_component",
    "RPLM_jerk_Y_component",
    "RPLM_jerk_Z_component",
    "LPLM_speed_magnitude",
    "LPLM_speed_X_component",
    "LPLM_speed_Y_component",
    "LPLM_speed_Z_component",
    "LPLM_acceleration_magnitude",
    "LPLM_acceleration_X_component",
    "LPLM_acceleration_Y_component",
    "LPLM_acceleration_Z_component",
    "LPLM_jerk_magnitude",
    "LPLM_jerk_X_component",
    "LPLM_jerk_Y_component",
    "LPLM_jerk_Z_component",
]

In [3]:
def f1scoremargin(ground_truth, predictions, tolerance):
    """
    Calcola l'F1 score con una finestra di tolleranza sui change points.
    
    :param ground_truth: Lista o array di change points reali
    :param predictions: Lista o array di change points predetti
    :param tolerance: La tolleranza temporale (numero di unità temporali)
    :return: precision, recall, f1-score
    """
    ground_truth = np.array(ground_truth)
    predictions = np.array(predictions)
    
    # Vettori per tracciare quali punti sono stati già associati
    matched_ground_truth = np.zeros(len(ground_truth), dtype=bool)
    matched_predictions = np.zeros(len(predictions), dtype=bool)

    mgt={key: False for key in ground_truth}
    mcp={key: False for key in predictions}
    #print(f'gt:{len(ground_truth)} - cp:{len(predictions)}')
    # True Positives (TP)
    tp = 0
    for i, gt_point in enumerate(ground_truth):
        for j, pred_point in enumerate(predictions):
            
            if not matched_predictions[j] and abs(gt_point - pred_point) <= tolerance:
                tp += 1
                matched_ground_truth[i] = True
                matched_predictions[j] = True

                mgt[gt_point] = True
                mcp[pred_point] = True
                break
            
    
    # False Positives (FP) - predizioni non corrispondenti a nessun ground truth entro la tolleranza
    fp = np.sum(~matched_predictions)
    
    # False Negatives (FN) - punti del ground truth non corrispondenti a nessuna predizione entro la tolleranza
    fn = np.sum(~matched_ground_truth)
    #print(f'tp:{tp} - fp:{fp} - fn:{fn}')
    #print(mgt)
    #print(mcp)
    # Calcolo di precision, recall e F1-score
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    #print(f'gt:{len(ground_truth)} cp:{len(predictions)} tp:{tp} fp:{fp} fn:{fn}')
    return precision, recall, f1, {"tp":tp, "fp":fp, "fn":fn}

In [4]:
def ReadAndPreProcess(inputDataRaw):
    # lettura
    df=pd.read_csv(inputDataRaw,sep=' ', header=None).interpolate()
    
    df=df.drop(0, axis=1)
    df=df.drop_duplicates()
    df = df.iloc[:, ::-1]
 

    return df

In [5]:
# questa funzione ritorna un dataframe del groundtruth che viene usato specificatamente per visualizzare il gt
# è soggetto a un preprocessing dei dati siccome l'ultimo groundtruth è dove termina il ts del gt
# di conseguenza per farlo corrispondere, bisogna stretcharlo
# ma ricordo di aver rifatti i dati nuovi per generare un groundtruth a fine ts, da controllare cosi che non serve stretcharlo?
def LoadingGroundTruth(df,gtraw):
    gt=pd.read_csv(gtraw,sep=' ', header=None)
    gt=gt.iloc[:,0].values
    #stretching dei dati se necessario per farlo corrispondere alla ts dei dati
    stretch_gt = np.array([])
    for idx,i in enumerate(gt):
        relpos = len(df)*i/gt[-1]
        stretch_gt = np.append(stretch_gt,relpos)

    # eliminiamo l'ultimo elemento che è stato annotato solo per delimitare la lunghezza della gt simile alla ts
    
    return stretch_gt[:-1]

In [6]:
def GetClasp2(df,gt,feature, p_idx, v_idx,**kwargs):
    
    result=np.array([])
    eachresult = []
    eachclasp=[]
    for i in feature:
        print(f'computing: {p_idx} / {v_idx} / {i}')
        ts=df.iloc[:,i]
        print(ts.values)
        
        
        clasp = BinaryClaSPSegmentation(**kwargs)
            
        found_cps = clasp.fit_predict(ts.values)    

        # c'è un bug con binseg dove un cp è oltre la lunghezza del ts
        # faccio un loop e se eccede cambio il valore con la len(tf)-1
        # WTF IS THIS
        """
        for i in range(0,len(found_cps)):
            if found_cps[i] >= len(ts):
                found_cps[i] = len(ts)-1
        """
        # per ogni array di cp di ogni singola feature
        # li unisco in un unico array. in pratica faccio un OR di tutti i cp
        result = np.sort(np.append(result,found_cps).flatten())
        #potenziale bug.
        #se faccio unique() mi toglie il numero di cp in un punto e quando faccio majority voting mi si toglie
        result = np.unique(result)
        eachresult.append(found_cps)
        eachclasp.append(clasp)
        
        

        
    return result, eachresult, eachclasp

In [7]:
# utilizzo CLASP 
# prende come parametro un dataframe e restituisce il clasp score
# gt e known vengono usati per usare il numero vero di cp se uguale a 1 sennò si cerca di predirlo se il modello lo permette
def GetClasp3(df,gt,known,feature, **kwargs):
    
    result=np.array([])
    eachresult = []
    eachclasp=[]
    for i in [feature]:
    
        ts=df.iloc[:,i]
        
        #print(ts.head())
        if known == 1:
            #print("knwon!")
            clasp = BinaryClaSPSegmentation(n_segments=len(gt), validation=None)
        else:
            #print("unknown!")
            clasp = BinaryClaSPSegmentation(**kwargs)
            
        found_cps = clasp.fit_predict(ts.values)    

        # c'è un bug con binseg dove un cp è oltre la lunghezza del ts
        # faccio un loop e se eccede cambio il valore con la len(tf)-1
        # WTF IS THIS
        """
        for i in range(0,len(found_cps)):
            if found_cps[i] >= len(ts):
                found_cps[i] = len(ts)-1
        """

        # per ogni array di cp di ogni singola feature
        # li unisco in un unico array. in pratica faccio un OR di tutti i cp
        result = np.sort(np.append(result,found_cps).flatten())
        result = np.unique(result)
        eachresult.append(found_cps)
        eachclasp.append(clasp)
        
        

        
    return result, eachresult, eachclasp

In [8]:
# utilizzo CLASP 
# prende come parametro un dataframe e restituisce il clasp score
# gt e known vengono usati per usare il numero vero di cp se uguale a 1 sennò si cerca di predirlo se il modello lo permette
def GetClasp(df,gt,known, **kwargs):
    
    result=np.array([])
    eachresult = []
    eachclasp=[]
    for i in range(0,len(features_name)):
    
        ts=df.iloc[:,i]
        
        #print(ts.head())
        if known == 1:
            #print("knwon!")
            clasp = BinaryClaSPSegmentation(n_segments=len(gt), validation=None)
        else:
            #print("unknown!")
            clasp = BinaryClaSPSegmentation(**kwargs)
            
        found_cps = clasp.fit_predict(ts.values)    

        # c'è un bug con binseg dove un cp è oltre la lunghezza del ts
        # faccio un loop e se eccede cambio il valore con la len(tf)-1
        # WTF IS THIS
        """
        for i in range(0,len(found_cps)):
            if found_cps[i] >= len(ts):
                found_cps[i] = len(ts)-1
        """
        # per ogni array di cp di ogni singola feature
        # li unisco in un unico array. in pratica faccio un OR di tutti i cp
        result = np.sort(np.append(result,found_cps).flatten())
        result = np.unique(result)
        eachresult.append(found_cps)
        eachclasp.append(clasp)
        
        

        
    return result, eachresult, eachclasp
        
    


In [9]:
def FPremoverDTW(featureTS,res,threshold):
     # controlla quale segmento piu lungo o corto
    # si fa una finestra grande quanto corto e slitta su lungo
    # si fa un dtw per ogni finestra e si prende lo score piu basso
    # se entro un certo limite si unisce, senno si continua
    if len(res) < 3:
        return res
    to_color=[]
    filtered=[res[0]]
    lo = 0
    hi = 1
    while hi < len(res)-1:
       # print(f'hi:{hi} max:{len(res)}')
        a = featureTS[int(res[lo]):int(res[hi])]
        b = featureTS[int(res[hi]):int(res[hi+1])]
        # controllo quale segmento piu lungo o corto
        # halflo = segmento piu corto è una timeseries
        # halfhi = segmento piu lungo è una timeseries
        if len(a) < len(b):
            halflo=featureTS[int(res[lo]):int(res[hi])]
            halfhi=featureTS[int(res[hi]):int(res[hi+1])]
        else:
            halfhi=featureTS[int(res[lo]):int(res[hi])]
            halflo=featureTS[int(res[hi]):int(res[hi+1])]

        # faccio sliding window e trovo la distance piu piccola
        st = 0
        en = len(halflo) # possibile bug
        smallestdist=-1
        smalllo=[]
        highlo=[]
      
       # print(f'en:{en} whilelim:{len(halfhi)}')
        while en < len(halfhi):
            
            slidewin = halfhi[st:en]
            halflo_d = np.array(halflo, dtype=np.double)
            slidewin_d = np.array(slidewin, dtype=np.double)
            distance = dtw.distance_fast(halflo_d, slidewin_d, use_pruning=True)
            if smallestdist == -1:
                smallestdist = distance
                smalllo=halflo
                highlo=slidewin
            elif smallestdist > distance:
                smallestdist = distance
                smalllo=halflo
                highlo=slidewin

            st+=30
            en+=30
            #print(f'en:{en} lim:{len(halfhi)} dist:{distance}')
        
        #plt.figure(figsize=(18,9))
        #plt.plot(np.arange(len(smalllo)),smalllo,"blue")
       # plt.figure(figsize=(18,9))
       # plt.plot(np.arange(len(highlo)),highlo,"green")
        #plt.xlabel(f'smallest:{smallestdist}')
        if smallestdist <= threshold:
            to_color.append(hi)
            hi+=1
        else:
            filtered.append(res[hi])
            lo=hi
            hi=lo+1
    filtered.append(res[-1])
    return filtered

In [10]:
timeseries=[
    "in\cora1_in.txt",
      "in\cora4_05_in.txt",
      "in\cora4_08_in.txt",
      "in\cora5_in.txt",
      "in\cora14_in.txt",
      "in\marianne7_in.txt",
      "in\marianne8_in.txt",
      "in\marianne10_in.txt",
      "in\marianne18_in.txt",
      "in\marianne19_in.txt",
      "in\marianne24_in.txt",
      "in\marianne26_in.txt",
      "in\marianne41_in.txt",
      "in\marianne42_in.txt",
      "in\marianne43_in.txt",
      "in\marianne47_in.txt",
      "in\marianne48_in.txt",
      "in\muriel18_in.txt",
      "in\muriel26_in.txt",
      "in\muriel27_in.txt",
      "in\muriel30_in.txt"

      ]
groundtruth=[
         "gt\cora_gt_2019-08-08_t001_video01.txt",
         "gt\cora_gt_2019-05-22_t004_video01.txt",
         "gt\cora_gt_2019-08-08_t004_video01.txt",
         "gt\cora5_gt.txt",
         "gt\cora_gt_2019-08-08_t014_video01.txt",
         "gt\marianne_gt_2016-03-22_t007_video01.txt",
         "gt\marianne_gt_2016-03-22_t008_video01.txt",
         "gt\marianne_gt_2016-03-22_t010_video01.txt",
         "gt\marianne_gt_2016-03-22_t018_video01.txt",
         "gt\marianne_gt_2016-03-22_t019_video01.txt",
         "gt\marianne_gt_2016-03-22_t024_video01.txt",
         "gt\marianne_gt_2016-03-22_t026_video01.txt",
         "gt\marianne_gt_2016-03-22_t041_video01.txt",
         "gt\marianne_gt_2016-03-22_t042_video01.txt",
         "gt\marianne_gt_2016-03-22_t043_video01.txt",
         "gt\marianne_gt_2016-03-22_t047_video01.txt",
         "gt\marianne_gt_2016-03-22_t048_video01.txt",
         "gt\muriel_gt_2016-03-21_t018_video01.txt",
         "gt\muriel_gt_2016-03-21_t026_video01.txt",
         "gt\muriel_gt_2016-03-21_t027_video01.txt",
         "gt\muriel_gt_2016-03-23_t030_video01.txt"
         ]



#suss
with open("../dfl.pkl", "rb") as f:
    dfl = pickle.load(f)

with open("../gtl.pkl", "rb") as f:
    gtl = pickle.load(f)

with open("../cpsl.pkl", "rb") as f:
    cpsl = pickle.load(f)

with open("../cpsl_suss_DTW.pkl", "rb") as f:
    cpsl_dtw = pickle.load(f)

#normalized
with open("../dfl_no.pkl", "rb") as f:
    dfl_no = pickle.load(f)

with open("../cpsl_no.pkl", "rb") as f:
    cpsl_no = pickle.load(f)

with open("../cpsl_no_DTW.pkl", "rb") as f:
    cpsl_no_dtw = pickle.load(f)

#standardized
with open("../dfl_st.pkl", "rb") as f:
    dfl_st = pickle.load(f)

with open("../cpsl_st.pkl", "rb") as f:
    cpsl_st = pickle.load(f)

with open("../cpsl_st_DTW.pkl", "rb") as f:
    cpsl_st_dtw = pickle.load(f)


<h1><b>FOR COMPUTING THE PREDICTION</b></h1>


# compute all cp for all timeseries, so later we can use it freely
dfl_st_z=[]
gtl_st_z=[]
cpsl_st_z=[]
for i in range(len(timeseries)):
    print(f'PRIMO LOOP:{i}/{len(timeseries)}')
    df_raw=ReadAndPreProcess(timeseries[i])
    scaler = StandardScaler()
    df_scaler = scaler.fit_transform(df_raw)
    df = pd.DataFrame(df_scaler)

    gt=LoadingGroundTruth(df,groundtruth[i])
    cp_all,cps,clasp=GetClasp2(df,gt,0,list(range(len(features_name))), window_size="suss",distance="euclidean_distance",n_jobs=6)
    dfl_st_z.append(df)
    gtl_st_z.append(gt)
    cpsl_st_z.append(cps)

with open("../dfl_st.pkl", "wb") as f:
    pickle.dump(dfl_st_z, f)

with open("../gtl_st.pkl", "wb") as f:
    pickle.dump(gtl_st_z, f)

with open("../cpsl_st.pkl", "wb") as f:
    pickle.dump(cpsl_st_z, f)

print("COMPLETATO PRIMA PARTE")

# compute all cp for all timeseries, so later we can use it freely
dfl_no_z=[]
gtl_no_z=[]
cpsl_no_z=[]
for i in range(len(timeseries)):
    print(f'SECONDO LOOP:{i}/{len(timeseries)}')
    df_raw=ReadAndPreProcess(timeseries[i])
    normalizer = MinMaxScaler()
    df_normalizer = normalizer.fit_transform(df_raw)
    df=pd.DataFrame(df_normalizer)
    gt=LoadingGroundTruth(df,groundtruth[i])
    cp_all,cps,clasp=GetClasp2(df,gt,0,list(range(len(features_name))), window_size="suss",distance="euclidean_distance",n_jobs=6)
    dfl_no_z.append(df)
    gtl_no_z.append(gt)
    cpsl_no_z.append(cps)

with open("../dfl_no.pkl", "wb") as f:
    pickle.dump(dfl_no_z, f)

with open("../gtl_no.pkl", "wb") as f:
    pickle.dump(gtl_no_z, f)

with open("../cpsl_no.pkl", "wb") as f:
    pickle.dump(cpsl_no_z, f)

<h1><b>FOR FILTERING WITH DTW</b></h1>

new_cpsl=[]
for i in range(len(timeseries)):
    print(f"computing: {i}/{len(timeseries)}")
    df=dfl_no[i]
    gt=gtl[i]
    cps=np.array(cpsl_no[i],dtype="object")
    new_cps=[]
    print("feature: ",end='')
    for idx,cp in enumerate(cps):
        
        print(f'{idx} ',end='')
        new_cp=FPremoverDTW(df.iloc[:,idx].values,cp)
        new_cps.append(new_cp)
    print("")
    new_cpsl.append(new_cps)

with open("../cpsl_no_DTW.pkl", "wb") as f:
    pickle.dump(new_cpsl, f)

new_cpsl=[]
for i in range(len(timeseries)):
    print(f"computing: {i}/{len(timeseries)}")
    df=dfl_st[i]
    gt=gtl[i]
    cps=np.array(cpsl_st[i],dtype="object")
    new_cps=[]
    print("feature: ",end='')
    for idx,cp in enumerate(cps):
        
        print(f'{idx} ',end='')
        new_cp=FPremoverDTW(df.iloc[:,idx].values,cp)
        new_cps.append(new_cp)
    print("")
    new_cpsl.append(new_cps)

with open("../cpsl_st_DTW.pkl", "wb") as f:
    pickle.dump(new_cpsl, f)

In [11]:
def UnionCPS(*val):
    res=np.array([])
    for i in val:
        res = np.append(res,i).flatten()
    return np.sort(res)

In [12]:
def MajorityVoteCP(arr,margin,amount):
    if len(arr)==0:
        return np.array([])
    # se vicino continua ad aggiungere

    # se lontano e bucket presente, generare medio

    # se lontano e bucket vuoto aggiornare start
    bucket=[]
    answer=[]

    for i in range(len(arr)-1,-1,-1):
        if bucket == []:
            bucket.append(arr[i])
        elif abs(arr[i]-bucket[-1]) <= margin:
            bucket.append(arr[i])
        elif abs(arr[i]-bucket[-1]) > margin:
            if len(bucket) < amount:
                bucket=[arr[i]]
            else:
                summ=0
                for j in bucket:
                    summ+=j
                answer.append(summ/len(bucket))
                bucket=[arr[i]]
    if len(bucket) < amount:
        bucket=[]
    else:
        summ=0
        for j in bucket:
            summ+=j
        answer.append(summ/len(bucket))
        bucket=[]
    return np.array(answer)


In [13]:
def delnear(arr,range):
    i = 0
    while i < len(arr) - 1:
        # Iniziamo con il primo elemento di un potenziale gruppo
        gruppo_inizio = i
        gruppo_fine = i

        # Cerca gli elementi che fanno parte dello stesso gruppo
        while gruppo_fine < len(arr) - 1 and arr[gruppo_fine + 1] - arr[gruppo_fine] < range:
            gruppo_fine += 1

        # Se esiste un gruppo di più elementi
        if gruppo_fine > gruppo_inizio:
            # Se la distanza tra l'inizio e la fine è minore di 50, elimina l'elemento maggiore (gruppo_fine)
            if arr[gruppo_fine] - arr[gruppo_inizio] < range:
                arr = np.delete(arr, gruppo_fine)
            
            # Elimina tutti gli elementi interni al gruppo
            arr = np.concatenate((arr[:gruppo_inizio + 1], arr[gruppo_fine:]))

        # Procedi con il prossimo gruppo
        i = gruppo_inizio + 1

    return arr

In [14]:
def IgnoreZone(idx,cpraw,gt):
    cp = cpraw.tolist()
    if idx == 0: #cora1
        for i in range(len(cp)-1, -1, -1):
            #if cp[i] > 3944.7118557910376+100 and cp[i] < 5911.693516853054-100 or cp[i] > 12845.0+100:
            if cp[i] > gt[18]+100 and cp[i] < gt[19]-100 or cp[i]> gt[-1]+100:
                cp.pop(i)
                
        
    elif idx == 1: #cora4_05
        for i in range(len(cp)-1, -1, -1):
            #if cp[i]< 969.6180827886711-100 and cp[i] > 13125.469063180826+100:
            if cp[i] < gt[0]-100 or cp[i] > gt[-1]+100:
                cp.pop(i)
    elif idx == 2: #cora4_08
        for i in range(len(cp)-1, -1, -1):
            #if cp[i] > 2874.607407407407+100 and cp[i] < 4016.935849056604-100:
            if cp[i] > gt[-2]+100 and cp[i] < gt[-1]-100:
                cp.pop(i)

    elif idx == 17: #muriel18
        for i in range(len(cp)-1, -1, -1):
            #if cp[i] > 180.03455207940698+100 and cp[i] < 1227.051137077522-100 or cp[i] > 5865.505591154668+100:
            if cp[i] > gt[0]+100 and cp[i] < gt[1]-100 or cp[i] > gt[-1]+100:
                cp.pop(i)

    elif idx == 18: #muriel26
        for i in range(len(cp)-1, -1, -1):
            #if cp[i] > 138.33224102186853+100 and cp[i] < 3677.231833076974-100:
            if cp[i] > gt[0]+100 and cp[i] < gt[1]-100:
                cp.pop(i)


    elif idx == 21: #muriel30
        for i in range(len(cp)-1, -1, -1):
            #if cp[i] > 8187.634803581529+100:
            if cp[i] > gt[26]+100 and cp[i] < gt[27]-100 or cp[i] > gt[-1]+100:
                cp.pop(i)


    else:
        pass
        #print("error IgnoreZone()")
    return np.array(cp)

In [15]:
# Dato una serie di cp, li combina in uno e fa il majority voting
def AndSal(margin,majvote,*args):
    result=np.array([])
 
    for cp in args:
        result = np.append(result,cp).flatten()
    result = np.sort(result)
    result = MajorityVoteCP(result,margin,majvote)
    return result


In [16]:
def UnionCP(cps,*val):
    res=np.array([])
    for i in val:
        res = np.append(res,cps[i]).flatten()
    return np.sort(res)

In [17]:
def together(cps,div):
    ariel_el=[26,27,28,29,30,31,32,33,34,35,36,37,2,8,14]
    ariel = UnionCPS(*cps[ariel_el])

    strn_el=[38,39,40,41,42,43,44,45,46,47,48,49,1,9]
    strn = UnionCPS(*cps[strn_el])

    rhel_el=[50,51,52,53,54,55,56,57,58,59,60,61,7,11,18,21]
    rhel = UnionCPS(*cps[rhel_el])

    lhel_el=[6,10,19,20,62,63,64,65,66,67,68,69,70,71,72,73]
    lhel = UnionCPS(*cps[lhel_el])
    
    rplm_el=[74,75,76,77,78,79,80,81,82,83,84,85,5,13,23,25]
    rplm = UnionCPS(*cps[rplm_el])

    lplm_el=[4,12,22,24,86,87,88,89,90,91,92,93,94,95,96,97]
    lplm = UnionCPS(*cps[lplm_el])

    
    ariel = MajorityVoteCP(ariel,100,div)#math.ceil(len(ariel_el)/div))
    strn = MajorityVoteCP(strn,100,div)#math.ceil(len(strn_el)/div))
    rhel = MajorityVoteCP(rhel,100,div)#math.ceil(len(rhel_el)/div))
    lhel = MajorityVoteCP(lhel,100,div)#math.ceil(len(lhel_el)/div))
    rplm = MajorityVoteCP(rplm,100,div)#math.ceil(len(rplm_el)/div))
    lplm = MajorityVoteCP(lplm,100,div)#math.ceil(len(lplm_el)/div))

    res = UnionCPS(ariel,strn,rhel,lhel,rplm,lplm)
    res = IgnoreZone(i,res,gt)
    res = delnear(res,100)
    
    _,_,f1,_=f1scoremargin(gt,res,100)
    return f1


In [18]:
def Comp4(cps,k,h):
    vel=cps[[26,27,28,29]]
    acc=cps[[30,31,32,33]]
    jerk=cps[[34,35,36,37]]
    ariel = AndSal(100,h,*AndSal(100,k,*vel),*AndSal(100,k,*acc),*AndSal(100,k,*jerk),UnionCP(cps,2,8,14))

    vel=cps[[38,39,40,41]]
    acc=cps[[42,43,44,45]]
    jerk=cps[[46,47,48,49]]
    strn = AndSal(100,h,*AndSal(100,k,*vel),*AndSal(100,k,*acc),*AndSal(100,k,*jerk),UnionCP(cps,1,9))
    
    vel=cps[[50,51,52,53]]
    acc=cps[[54,55,56,57]]
    jerk=cps[[58,59,60,61]]
    rhel=AndSal(100,h,*AndSal(100,k,*vel),*AndSal(100,k,*acc),*AndSal(100,k,*jerk),UnionCP(cps,7,11,18,21))

    vel=cps[[62,63,64,65]]
    acc=cps[[66,67,68,69]]
    jerk=cps[[70,71,72,73]]
    lhel=AndSal(100,h,*AndSal(100,k,*vel),*AndSal(100,k,*acc),*AndSal(100,k,*jerk),UnionCP(cps,6,10,19,20))

    vel=cps[[74,75,76,77]]
    acc=cps[[78,79,80,81]]
    jerk=cps[[82,83,84,85]]
    rplm=AndSal(100,h,*AndSal(100,k,*vel),*AndSal(100,k,*acc),*AndSal(100,k,*jerk),UnionCP(cps,5,13,23,25))

    vel=cps[[86,87,88,89]]
    acc=cps[[90,91,92,93]]
    jerk=cps[[94,95,96,97]]
    lplm=AndSal(100,h,*AndSal(100,2,*vel),*AndSal(100,2,*acc),*AndSal(100,2,*jerk),UnionCP(cps,4,12,22,24))

    # unisco il tutto in un unico array
    final = UnionCPS(ariel,strn,rhel,lhel,rplm,lplm)
    final = delnear(final,100)
    final = IgnoreZone(i,final,gt)

    _,_,f1,_=f1scoremargin(gt,final,100)

    return f1


In [19]:
def test(lol,**kwargs):
    print(lol)
    print(kwargs)
    print(**kwargs)


In [20]:
param_grid = {
    "window_size": ['suss'],
    "distance": ['euclidean_distance'],
    "score":['roc_auc','f1'],
    "early_stopping": [True,False],
    "k_neighbours":[1,3,5,7,9],
    "n_jobs":[4]
}


# 21*98 = 2058 timeseries
for p_idx,params in enumerate(ParameterGrid(param_grid)):
    if p_idx < 13:
        print(f'skipped:{p_idx}')
        continue
    params["excl_radius"]=params["k_neighbours"]+2
    cpsl=[]
    for i in range(len(timeseries)):
        df=ReadAndPreProcess(timeseries[i])
        gt=LoadingGroundTruth(df,groundtruth[i])
        #cp_all,cps,clasp=GetClasp2(df,gt,0,list(range(len(features_name))), window_size="suss",distance="euclidean_distance",n_jobs=6)
        cp_all,cps,clasp=GetClasp2(df,gt,list(range(len(features_name))),p_idx,i, **params)
        cpsl.append(cps)


    with open("../cpsl_param_"+str(p_idx)+".pkl", "wb") as f:
        pickle.dump(cpsl, f)


skipped:0
skipped:1
skipped:2
skipped:3
skipped:4
skipped:5
skipped:6
skipped:7
skipped:8
skipped:9
skipped:10
skipped:11
skipped:12
computing: 13 / 0 / 0
[0.       0.011978 0.011978 ... 0.07526  0.072244 0.067064]


C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\claspy\nearest_neighbour.py:252: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  start, end = pranges[idx]


computing: 13 / 0 / 1
[0.       0.       0.       ... 0.130845 0.123262 0.120738]
computing: 13 / 0 / 2
[0.       0.       0.       ... 0.755605 0.757314 0.759079]
computing: 13 / 0 / 3
[430.243661 430.171766 430.171766 ... 540.41448  540.433874 540.452042]
computing: 13 / 0 / 4
[0.       0.       0.       ... 0.874497 0.817759 0.765728]
computing: 13 / 0 / 5
[0.       0.       0.       ... 0.335698 0.310352 0.28195 ]
computing: 13 / 0 / 6
[0.       0.       0.       ... 0.00088  0.00072  0.000796]
computing: 13 / 0 / 7
[0.       0.       0.       ... 0.003527 0.003608 0.003692]
computing: 13 / 0 / 8
[0.       0.       0.       ... 0.314741 0.311076 0.308231]
computing: 13 / 0 / 9
[393.78201  393.78872  393.78872  ... 399.8061   399.795541 399.80684 ]
computing: 13 / 0 / 10
[370.462323 370.464987 370.464987 ... 376.353524 376.359062 376.38521 ]
computing: 13 / 0 / 11
[374.056052 374.062478 374.062478 ... 382.164126 382.157933 382.189832]
computing: 13 / 0 / 12
[184.66781  184.570526 18

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 13 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 13 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 13 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 13 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 13 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 13 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 13 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 13 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 13 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 13 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 2 / 79
[ 0.        0.        0.       ... -0.435233 -0.434467 -0.419949]
computing: 13 / 2 / 80
[0.       0.       0.       ... 0.22542  0.166752 0.107525]
computing: 13 / 2 / 81
[0.       0.       0.       ... 0.081399 0.038603 0.004076]
computing: 13 / 2 / 82
[0.       0.       0.       ... 0.026387 0.02511  0.024441]
computing: 13 / 2 / 83
[-0.       -0.       -0.       ... -0.00267   0.000974  0.005686]
computing: 13 / 2 / 84
[ 0.        0.        0.       ... -0.020579 -0.020388 -0.020543]
computing: 13 / 2 / 85
[ 0.        0.        0.       ... -0.016298 -0.014625 -0.011959]
computing: 13 / 2 / 86
[0.       0.       0.       ... 3.146711 3.14939  3.09574 ]
computing: 13 / 2 / 87
[ 0.        0.        0.       ... -0.056772 -0.037413 -0.064982]
computing: 13 / 2 / 88
[0.       0.       0.       ... 2.93362  2.953284 2.920055]
computing: 13 / 2 / 89
[ 0.        0.        0.       ... -1.136854 -1.093329 -1.025994]
computing: 13 / 2 / 90
[0.       0.       0.       

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 3 / 1
[0.       0.       0.001119 ... 0.002361 0.001947 0.001546]
computing: 13 / 3 / 2
[0.       0.       0.       ... 0.734876 0.738998 0.743405]
computing: 13 / 3 / 3
[417.52125  417.443845 417.44894  ... 540.590764 540.576683 540.571312]
computing: 13 / 3 / 4
[0.       0.       0.009099 ... 0.222445 0.188894 0.150903]
computing: 13 / 3 / 5
[0.       0.       0.006499 ... 0.372376 0.322559 0.280348]
computing: 13 / 3 / 6
[0.00e+00 0.00e+00 8.00e-06 ... 1.80e-04 2.43e-04 3.35e-04]
computing: 13 / 3 / 7
[0.00e+00 0.00e+00 9.00e-06 ... 4.32e-04 2.98e-04 1.98e-04]
computing: 13 / 3 / 8
[0.       0.       0.000581 ... 0.006445 0.005664 0.005051]
computing: 13 / 3 / 9
[415.922779 415.913472 415.869246 ... 420.346462 420.346543 420.351165]
computing: 13 / 3 / 10
[370.833062 370.842306 370.809205 ... 372.121842 372.119229 372.128873]
computing: 13 / 3 / 11
[370.802328 370.799999 370.756612 ... 369.573805 369.574926 369.578797]
computing: 13 / 3 / 12
[191.204018 191.358968 19

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 4 / 4
[0.       0.       0.       ... 0.010456 0.010336 0.009253]
computing: 13 / 4 / 5
[0.       0.       0.       ... 0.87352  0.924489 0.947991]
computing: 13 / 4 / 6
[0.       0.       0.       ... 0.007273 0.00914  0.011139]
computing: 13 / 4 / 7
[0.       0.       0.       ... 0.005291 0.00557  0.00506 ]
computing: 13 / 4 / 8
[0.       0.       0.       ... 0.108221 0.107715 0.104452]
computing: 13 / 4 / 9
[392.81405  392.81405  392.927583 ... 392.208856 392.204876 392.178083]
computing: 13 / 4 / 10
[366.084246 366.084246 366.162556 ... 366.737293 366.732539 366.721312]
computing: 13 / 4 / 11
[374.260236 374.260236 374.308636 ... 372.582858 372.583702 372.551752]
computing: 13 / 4 / 12
[186.937968 186.937968 186.911817 ... 252.929689 252.854466 252.792082]
computing: 13 / 4 / 13
[195.100405 195.100405 195.393616 ... 266.067168 265.946243 265.880074]
computing: 13 / 4 / 14
[200.775339 200.775339 200.841307 ... 204.85301  204.911047 204.93466 ]
computing: 13 / 4 / 1

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 6 / 20
[8.970269 8.970269 7.661708 ... 7.672244 7.672244 7.706262]
computing: 13 / 6 / 21
[10.400875 10.400875 10.011449 ...  9.407391  9.407391  9.40788 ]
computing: 13 / 6 / 22
[98.877354 98.877354 97.113428 ... 98.701993 98.701993 98.690511]
computing: 13 / 6 / 23
[100.722372 100.722372 100.482932 ... 100.192865 100.192865 100.143164]
computing: 13 / 6 / 24
[5.173114 5.173114 3.442476 ... 4.55332  4.55332  4.541165]
computing: 13 / 6 / 25
[164.643285 164.643285 166.748358 ... 167.292215 167.292215 167.276917]
computing: 13 / 6 / 26
[0.       0.       0.010846 ... 0.129955 0.112488 0.102965]
computing: 13 / 6 / 27
[ 0.        0.        0.010712 ... -0.112328 -0.101568 -0.099252]
computing: 13 / 6 / 28
[ 0.        0.        0.001315 ... -0.006495 -0.000926  0.004444]
computing: 13 / 6 / 29
[-0.       -0.        0.001083 ...  0.065026  0.048338  0.027038]
computing: 13 / 6 / 30
[0.       0.       0.002062 ... 0.008299 0.008725 0.009597]
computing: 13 / 6 / 31
[ 0.      

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 7 / 20
[7.664473 7.664473 7.495214 ... 8.680954 8.680954 8.660813]
computing: 13 / 7 / 21
[10.005124 10.005124 10.463897 ... 13.273089 13.273089 13.189314]
computing: 13 / 7 / 22
[ 97.101915  97.101915  98.837496 ... 103.57707  103.57707  103.571709]
computing: 13 / 7 / 23
[100.498625 100.498625 102.327325 ... 102.669924 102.669924 102.588903]
computing: 13 / 7 / 24
[3.424789 3.424789 2.326449 ... 3.72725  3.72725  3.701116]
computing: 13 / 7 / 25
[166.762015 166.762015 166.178362 ... 167.092506 167.092506 167.13475 ]
computing: 13 / 7 / 26
[0.       0.       0.003325 ... 0.571255 0.565691 0.558729]
computing: 13 / 7 / 27
[ 0.        0.       -0.000657 ... -0.47075  -0.458943 -0.443099]
computing: 13 / 7 / 28
[-0.       -0.       -0.000271 ... -0.02285  -0.031527 -0.038865]
computing: 13 / 7 / 29
[-0.       -0.       -0.003248 ...  0.322808  0.329216  0.338128]
computing: 13 / 7 / 30
[0.       0.       0.000632 ... 0.009039 0.010437 0.012084]
computing: 13 / 7 / 31
[0. 

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 8 / 18
[166.180306 166.180306 164.45856  ... 162.535227 162.45178  162.45178 ]
computing: 13 / 8 / 19
[166.037656 166.037656 164.879312 ... 163.807732 163.839105 163.839105]
computing: 13 / 8 / 20
[7.48082  7.48082  8.569317 ... 7.036852 7.004084 7.004084]
computing: 13 / 8 / 21
[10.477273 10.477273 10.190929 ... 10.654758 10.687227 10.687227]
computing: 13 / 8 / 22
[ 98.844147  98.844147 100.913268 ... 105.833259 105.643203 105.643203]
computing: 13 / 8 / 23
[102.356686 102.356686 101.294656 ... 105.725197 105.618511 105.618511]
computing: 13 / 8 / 24
[2.351972 2.351972 4.522037 ... 6.059645 6.074783 6.074783]
computing: 13 / 8 / 25
[166.186397 166.186397 166.507819 ... 165.849201 165.749649 165.749649]
computing: 13 / 8 / 26
[0.       0.       0.004621 ... 0.51027  0.49132  0.473883]
computing: 13 / 8 / 27
[-0.       -0.       -0.002591 ...  0.440462  0.427586  0.415597]
computing: 13 / 8 / 28
[ 0.        0.       -0.000928 ... -0.030867 -0.019931 -0.007912]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 10 / 13
[290.62921  290.614024 290.680775 ... 292.47356  292.498501 292.493271]
computing: 13 / 10 / 14
[149.555601 149.559458 149.667173 ... 152.286423 152.276054 152.273878]
computing: 13 / 10 / 15
[2.08192  2.08192  1.948894 ... 2.048085 2.061712 2.061712]
computing: 13 / 10 / 16
[11.720478 11.720478 11.824505 ...  9.708432  9.726116  9.726116]
computing: 13 / 10 / 17
[5.720104 5.720104 6.012688 ... 6.8258   6.772708 6.772708]
computing: 13 / 10 / 18
[164.146352 164.146352 166.504689 ... 168.660701 168.549516 168.549516]
computing: 13 / 10 / 19
[164.490899 164.490899 166.231962 ... 166.042959 166.021143 166.021143]
computing: 13 / 10 / 20
[7.881764 7.881764 8.034573 ... 7.617201 7.552489 7.552489]
computing: 13 / 10 / 21
[ 9.939354  9.939354 10.194165 ...  9.416258  9.38604   9.38604 ]
computing: 13 / 10 / 22
[ 98.838329  98.838329  97.965925 ... 100.140498 100.074878 100.074878]
computing: 13 / 10 / 23
[ 98.417046  98.417046 102.164517 ... 100.990022 100.95939  100.

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 13 / 6
[0.00e+00 0.00e+00 1.00e-06 ... 4.75e-04 3.57e-04 3.13e-04]
computing: 13 / 13 / 7
[0.       0.       0.       ... 0.002453 0.001988 0.001626]
computing: 13 / 13 / 8
[0.00000e+00 0.00000e+00 5.20000e-05 ... 4.17043e-01 3.88379e-01
 3.66107e-01]
computing: 13 / 13 / 9
[454.837206 454.834576 455.014238 ... 452.09812  452.096097 452.097812]
computing: 13 / 13 / 10
[399.86153  399.857331 399.892011 ... 398.311989 398.312597 398.308224]
computing: 13 / 13 / 11
[402.426367 402.421103 402.542422 ... 398.73232  398.725298 398.729552]
computing: 13 / 13 / 12
[303.777757 303.794644 303.67377  ... 304.024775 304.019628 304.041136]
computing: 13 / 13 / 13
[301.478953 301.478981 301.544792 ... 297.505755 297.524725 297.561017]
computing: 13 / 13 / 14
[144.290306 144.279963 144.261977 ... 148.342929 148.336619 148.343069]
computing: 13 / 13 / 15
[2.904989 2.904989 1.790657 ... 1.933252 1.933988 1.933988]
computing: 13 / 13 / 16
[10.74004  10.74004   8.565377 ...  9.395995  9.4

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 14 / 7
[0.0e+00 0.0e+00 0.0e+00 ... 4.0e-06 2.1e-05 7.2e-05]
computing: 13 / 14 / 8
[0.00000e+00 0.00000e+00 2.80000e-05 ... 1.63453e-01 1.23136e-01
 9.11040e-02]
computing: 13 / 14 / 9
[449.94743  449.94864  450.053029 ... 452.654879 452.687772 452.707293]
computing: 13 / 14 / 10
[397.042827 397.042929 397.098205 ... 400.113123 400.162116 400.180213]
computing: 13 / 14 / 11
[399.774288 399.775746 399.869162 ... 400.553904 400.576203 400.596073]
computing: 13 / 14 / 12
[305.295834 305.311984 305.237385 ... 300.85565  300.849713 300.851151]
computing: 13 / 14 / 13
[298.514356 298.526724 298.594718 ... 296.823666 296.824453 296.830975]
computing: 13 / 14 / 14
[144.914098 144.90722  144.949625 ... 145.673925 145.670297 145.675149]
computing: 13 / 14 / 15
[1.796774 1.796774 3.110733 ... 2.10715  2.110484 2.110484]
computing: 13 / 14 / 16
[ 8.561946  8.561946 10.673954 ...  8.388552  8.400005  8.400005]
computing: 13 / 14 / 17
[6.271583 6.271583 3.926278 ... 3.413992 3.41222

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 18 / 8
[0.00000e+00 0.00000e+00 9.90000e-05 ... 3.66368e-01 3.42340e-01
 3.07818e-01]
computing: 13 / 18 / 9
[430.037301 430.037549 430.114318 ... 427.750873 427.757416 427.759384]
computing: 13 / 18 / 10
[388.572765 388.566703 388.608459 ... 385.583688 385.566843 385.562854]
computing: 13 / 18 / 11
[386.214669 386.202463 386.260627 ... 387.567371 387.602568 387.638763]
computing: 13 / 18 / 12
[291.854949 291.87402  291.92285  ... 296.592155 296.485124 296.3691  ]
computing: 13 / 18 / 13
[288.570845 288.571315 288.687927 ... 286.570603 286.560942 286.538014]
computing: 13 / 18 / 14
[147.649873 147.640602 147.725563 ... 150.409346 150.420289 150.441969]
computing: 13 / 18 / 15
[ 7.813312  7.813312 10.210543 ... 11.334835 11.341779 11.341779]
computing: 13 / 18 / 16
[17.210725 17.210725 20.269639 ... 18.372276 18.406812 18.406812]
computing: 13 / 18 / 17
[0.537529 0.537529 2.553801 ... 6.210732 6.241347 6.241347]
computing: 13 / 18 / 18
[170.838235 170.838235 169.460547 .

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 19 / 25
[158.870327 158.870327 158.575233 ... 158.098106 158.092992 158.092992]
computing: 13 / 19 / 26
[0.       0.       0.003329 ... 0.292444 0.273857 0.263317]
computing: 13 / 19 / 27
[-0.       -0.       -0.002707 ...  0.276014  0.239055  0.203051]
computing: 13 / 19 / 28
[-0.       -0.        0.000928 ... -0.018655 -0.012863 -0.006727]
computing: 13 / 19 / 29
[-0.       -0.       -0.001702 ...  0.094824  0.132985  0.167514]
computing: 13 / 19 / 30
[0.       0.       0.000633 ... 0.024831 0.024988 0.024568]
computing: 13 / 19 / 31
[-0.       -0.        0.000515 ... -0.019291 -0.018811 -0.018166]
computing: 13 / 19 / 32
[ 0.        0.       -0.000176 ...  0.002494  0.002741  0.002811]
computing: 13 / 19 / 33
[0.       0.       0.000324 ... 0.015434 0.016219 0.016299]
computing: 13 / 19 / 34
[0.       0.       0.000164 ... 0.000302 0.000199 0.000213]
computing: 13 / 19 / 35
[-0.       -0.        0.000133 ...  0.000221  0.000174  0.000134]
computing: 13 / 19 / 36
[ 0.

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 13 / 20 / 6
[0.000e+00 0.000e+00 3.000e-06 ... 6.390e-04 1.153e-03 1.301e-03]
computing: 13 / 20 / 7
[0.00e+00 0.00e+00 1.00e-06 ... 4.85e-04 5.58e-04 6.85e-04]
computing: 13 / 20 / 8
[0.       0.       0.00032  ... 0.063298 0.075962 0.095416]
computing: 13 / 20 / 9
[439.284228 439.264287 439.255491 ... 439.318524 439.195494 439.112379]
computing: 13 / 20 / 10
[389.245671 389.228846 389.23995  ... 388.701495 388.63549  388.61007 ]
computing: 13 / 20 / 11
[385.596973 385.57361  385.580295 ... 387.83602  387.756484 387.734667]
computing: 13 / 20 / 12
[308.681281 308.705914 308.841433 ... 246.116086 244.473627 242.794394]
computing: 13 / 20 / 13
[294.716075 294.738921 294.74539  ... 242.864617 241.260435 239.691464]
computing: 13 / 20 / 14
[141.871142 141.871846 141.902055 ... 146.70188  146.779968 146.867608]
computing: 13 / 20 / 15
[9.406114 9.406114 8.115465 ... 7.040429 7.040429 7.025013]
computing: 13 / 20 / 16
[18.674618 18.674618 19.881188 ... 16.926877 16.926877 16.9238

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 14 / 0 / 18
[173.165021 173.165021 175.545826 ... 173.617258 173.617258 173.642272]
computing: 14 / 0 / 19
[175.786043 175.786043 175.811794 ... 175.694049 175.694049 175.716371]
computing: 14 / 0 / 20
[17.666418 17.666418 17.653417 ... 17.597218 17.597218 17.607634]
computing: 14 / 0 / 21
[14.296195 14.296195 15.212399 ... 14.247656 14.247656 14.218168]
computing: 14 / 0 / 22
[110.70678  110.70678  171.52414  ... 110.434674 110.434674 110.344449]
computing: 14 / 0 / 23
[105.451157 105.451157 166.171253 ... 104.961613 104.961613 104.852964]
computing: 14 / 0 / 24
[41.566953 41.566953 44.243274 ... 41.944791 41.944791 41.914727]
computing: 14 / 0 / 25
[167.26115  167.26115  159.787515 ... 167.158617 167.158617 167.087325]
computing: 14 / 0 / 26
[0.       0.       0.       ... 0.561018 0.557742 0.555186]
computing: 14 / 0 / 27
[ 0.        0.        0.       ... -0.009366 -0.036212 -0.062477]
computing: 14 / 0 / 28
[-0.       -0.       -0.       ...  0.491446  0.495759  0.50028

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 14 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 14 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 14 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 14 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 14 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 14 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 14 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 14 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 14 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 14 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 14 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 14 / 13 / 15
[2.904989 2.904989 1.790657 ... 1.933252 1.933988 1.933988]
computing: 14 / 13 / 16
[10.74004  10.74004   8.565377 ...  9.395995  9.40737   9.40737 ]
computing: 14 / 13 / 17
[4.791818 4.791818 6.278415 ... 4.806771 4.803759 4.803759]
computing: 14 / 13 / 18
[168.702958 168.702958 165.355783 ... 170.688504 170.70429  170.70429 ]
computing: 14 / 13 / 19
[172.847365 172.847365 169.132284 ... 171.835921 171.907088 171.907088]
computing: 14 / 13 / 20
[5.612589 5.612589 4.349407 ... 6.546211 6.543695 6.543695]
computing: 14 / 13 / 21
[10.381771 10.381771 10.529231 ...  9.119981  9.101141  9.101141]
computing: 14 / 13 / 22
[ 99.955064  99.955064  97.706282 ... 100.160395 100.063235 100.063235]
computing: 14 / 13 / 23
[102.511616 102.511616  98.866712 ... 103.174095 103.055095 103.055095]
computing: 14 / 13 / 24
[5.209501 5.209501 6.576638 ... 5.834056 5.837052 5.837052]
computing: 14 / 13 / 25
[162.124736 162.124736 162.153332 ... 163.102888 163.109798 163.109798]
comp

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 14 / 18 / 8
[0.00000e+00 0.00000e+00 9.90000e-05 ... 3.66368e-01 3.42340e-01
 3.07818e-01]
computing: 14 / 18 / 9
[430.037301 430.037549 430.114318 ... 427.750873 427.757416 427.759384]
computing: 14 / 18 / 10
[388.572765 388.566703 388.608459 ... 385.583688 385.566843 385.562854]
computing: 14 / 18 / 11
[386.214669 386.202463 386.260627 ... 387.567371 387.602568 387.638763]
computing: 14 / 18 / 12
[291.854949 291.87402  291.92285  ... 296.592155 296.485124 296.3691  ]
computing: 14 / 18 / 13
[288.570845 288.571315 288.687927 ... 286.570603 286.560942 286.538014]
computing: 14 / 18 / 14
[147.649873 147.640602 147.725563 ... 150.409346 150.420289 150.441969]
computing: 14 / 18 / 15
[ 7.813312  7.813312 10.210543 ... 11.334835 11.341779 11.341779]
computing: 14 / 18 / 16
[17.210725 17.210725 20.269639 ... 18.372276 18.406812 18.406812]
computing: 14 / 18 / 17
[0.537529 0.537529 2.553801 ... 6.210732 6.241347 6.241347]
computing: 14 / 18 / 18
[170.838235 170.838235 169.460547 .

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 14 / 20 / 19
[173.992899 173.992899 170.1429   ... 172.001827 172.001827 172.214412]
computing: 14 / 20 / 20
[ 8.889603  8.889603 11.51936  ...  9.964896  9.964896  9.982639]
computing: 14 / 20 / 21
[ 9.970587  9.970587 10.830654 ... 10.110382 10.110382 10.15404 ]
computing: 14 / 20 / 22
[ 89.829509  89.829509  90.464056 ... 139.928627 139.928627 142.526168]
computing: 14 / 20 / 23
[100.417595 100.417595 102.408578 ... 145.262366 145.262366 148.092618]
computing: 14 / 20 / 24
[20.777415 20.777415 14.815429 ... 15.419998 15.419998 15.351967]
computing: 14 / 20 / 25
[158.623224 158.623224 157.67172  ... 159.105974 159.105974 159.123524]
computing: 14 / 20 / 26
[0.       0.       0.017894 ... 0.251591 0.275613 0.308895]
computing: 14 / 20 / 27
[-0.       -0.        0.016435 ... -0.011828 -0.022022 -0.037747]
computing: 14 / 20 / 28
[-0.       -0.       -0.001469 ... -0.0644   -0.066209 -0.061404]
computing: 14 / 20 / 29
[ 0.        0.       -0.006922 ...  0.242922  0.266634  0.

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 0 / 18
[173.165021 173.165021 175.545826 ... 173.617258 173.617258 173.642272]
computing: 15 / 0 / 19
[175.786043 175.786043 175.811794 ... 175.694049 175.694049 175.716371]
computing: 15 / 0 / 20
[17.666418 17.666418 17.653417 ... 17.597218 17.597218 17.607634]
computing: 15 / 0 / 21
[14.296195 14.296195 15.212399 ... 14.247656 14.247656 14.218168]
computing: 15 / 0 / 22
[110.70678  110.70678  171.52414  ... 110.434674 110.434674 110.344449]
computing: 15 / 0 / 23
[105.451157 105.451157 166.171253 ... 104.961613 104.961613 104.852964]
computing: 15 / 0 / 24
[41.566953 41.566953 44.243274 ... 41.944791 41.944791 41.914727]
computing: 15 / 0 / 25
[167.26115  167.26115  159.787515 ... 167.158617 167.158617 167.087325]
computing: 15 / 0 / 26
[0.       0.       0.       ... 0.561018 0.557742 0.555186]
computing: 15 / 0 / 27
[ 0.        0.        0.       ... -0.009366 -0.036212 -0.062477]
computing: 15 / 0 / 28
[-0.       -0.       -0.       ...  0.491446  0.495759  0.50028

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 15 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 15 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 15 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 15 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 15 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 15 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 15 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 15 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 15 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 15 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 3 / 28
[-0.       -0.       -0.00553  ...  0.021875  0.01882   0.014434]
computing: 15 / 3 / 29
[ 0.        0.       -0.01659  ...  0.021124  0.030381  0.040543]
computing: 15 / 3 / 30
[0.       0.       0.004583 ... 0.003085 0.003733 0.003888]
computing: 15 / 3 / 31
[ 0.        0.        0.003154 ... -0.001332 -0.001877 -0.001853]
computing: 15 / 3 / 32
[ 0.        0.        0.001051 ... -0.001027 -0.001196 -0.001189]
computing: 15 / 3 / 33
[0.       0.       0.003154 ... 0.002587 0.002997 0.003204]
computing: 15 / 3 / 34
[0.000e+00 0.000e+00 1.188e-03 ... 5.130e-04 2.660e-04 7.400e-05]
computing: 15 / 3 / 35
[ 0.00e+00  0.00e+00  8.18e-04 ... -3.89e-04 -1.88e-04  5.80e-05]
computing: 15 / 3 / 36
[ 0.00e+00  0.00e+00  2.73e-04 ... -1.58e-04 -1.24e-04 -4.10e-05]
computing: 15 / 3 / 37
[ 0.00e+00  0.00e+00  8.18e-04 ...  2.94e-04  1.42e-04 -2.20e-05]
computing: 15 / 3 / 38
[0.       0.       0.033451 ... 0.048585 0.044125 0.039317]
computing: 15 / 3 / 39
[ 0.        0.  

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 10 / 76
[-0.       -0.        0.008469 ... -0.39253  -0.340544 -0.280177]
computing: 15 / 10 / 77
[ 0.        0.       -0.001121 ... -0.18393  -0.183723 -0.187904]
computing: 15 / 10 / 78
[0.       0.       0.002865 ... 0.02459  0.027155 0.029389]
computing: 15 / 10 / 79
[ 0.        0.       -0.00236  ... -0.00165   0.001307  0.003386]
computing: 15 / 10 / 80
[ 0.        0.       -0.00161  ...  0.02453   0.027123  0.029181]
computing: 15 / 10 / 81
[ 0.        0.        0.000213 ...  0.00046  -0.000132 -0.000831]
computing: 15 / 10 / 82
[0.       0.       0.000743 ... 0.001569 0.001321 0.000956]
computing: 15 / 10 / 83
[ 0.        0.       -0.000612 ...  0.001164  0.000818  0.000464]
computing: 15 / 10 / 84
[ 0.        0.       -0.000417 ...  0.000986  0.000972  0.000804]
computing: 15 / 10 / 85
[ 0.00e+00  0.00e+00  5.50e-05 ... -3.66e-04 -3.61e-04 -2.28e-04]
computing: 15 / 10 / 86
[0.       0.       0.007271 ... 0.258719 0.220789 0.219129]
computing: 15 / 10 / 87
[0. 

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 13 / 26
[0.       0.       0.007231 ... 0.645789 0.6232   0.605068]
computing: 15 / 13 / 27
[-0.       -0.       -0.000696 ...  0.103957  0.086906  0.064907]
computing: 15 / 13 / 28
[-0.       -0.        0.000271 ...  0.019496  0.010778  0.001987]
computing: 15 / 13 / 29
[-0.       -0.       -0.007193 ... -0.637068 -0.617017 -0.601573]
computing: 15 / 13 / 30
[0.       0.       0.001375 ... 0.013868 0.014943 0.016284]
computing: 15 / 13 / 31
[ 0.        0.        0.000132 ... -0.010037 -0.01128  -0.012839]
computing: 15 / 13 / 32
[ 0.000e+00  0.000e+00 -5.100e-05 ... -2.614e-03 -2.986e-03 -3.088e-03]
computing: 15 / 13 / 33
[0.       0.       0.001368 ... 0.009205 0.009335 0.009529]
computing: 15 / 13 / 34
[0.       0.       0.000356 ... 0.000424 0.000579 0.000671]
computing: 15 / 13 / 35
[ 0.00e+00  0.00e+00  3.40e-05 ... -3.97e-04 -5.74e-04 -6.61e-04]
computing: 15 / 13 / 36
[ 0.00e+00  0.00e+00 -1.30e-05 ... -1.48e-04 -1.90e-05  9.30e-05]
computing: 15 / 13 / 37
[ 0.

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 17 / 11
[390.292543 390.198192 390.225558 ... 392.765577 392.769764 392.765202]
computing: 15 / 17 / 12
[300.004176 300.02294  299.899388 ... 290.239078 288.966238 287.737209]
computing: 15 / 17 / 13
[285.969209 285.990442 286.089004 ... 280.713221 279.590872 278.190173]
computing: 15 / 17 / 14
[155.740777 155.702776 155.745565 ... 152.101852 151.637361 151.153389]
computing: 15 / 17 / 15
[2.562968 2.562968 7.801618 ... 9.863477 9.863477 9.832006]
computing: 15 / 17 / 16
[10.682276 10.682276 17.236842 ... 17.264858 17.264858 17.19578 ]
computing: 15 / 17 / 17
[5.392397 5.392397 0.506831 ... 5.812613 5.812613 5.835232]
computing: 15 / 17 / 18
[164.508289 164.508289 170.813256 ... 171.471517 171.471517 171.636123]
computing: 15 / 17 / 19
[166.507729 166.507729 171.233252 ... 167.934186 167.934186 168.135918]
computing: 15 / 17 / 20
[ 4.995085  4.995085 10.15508  ... 11.377481 11.377481 11.4659  ]
computing: 15 / 17 / 21
[10.85928  10.85928   7.754072 ... 13.723386 13.7233

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 18 / 8
[0.00000e+00 0.00000e+00 9.90000e-05 ... 3.66368e-01 3.42340e-01
 3.07818e-01]
computing: 15 / 18 / 9
[430.037301 430.037549 430.114318 ... 427.750873 427.757416 427.759384]
computing: 15 / 18 / 10
[388.572765 388.566703 388.608459 ... 385.583688 385.566843 385.562854]
computing: 15 / 18 / 11
[386.214669 386.202463 386.260627 ... 387.567371 387.602568 387.638763]
computing: 15 / 18 / 12
[291.854949 291.87402  291.92285  ... 296.592155 296.485124 296.3691  ]
computing: 15 / 18 / 13
[288.570845 288.571315 288.687927 ... 286.570603 286.560942 286.538014]
computing: 15 / 18 / 14
[147.649873 147.640602 147.725563 ... 150.409346 150.420289 150.441969]
computing: 15 / 18 / 15
[ 7.813312  7.813312 10.210543 ... 11.334835 11.341779 11.341779]
computing: 15 / 18 / 16
[17.210725 17.210725 20.269639 ... 18.372276 18.406812 18.406812]
computing: 15 / 18 / 17
[0.537529 0.537529 2.553801 ... 6.210732 6.241347 6.241347]
computing: 15 / 18 / 18
[170.838235 170.838235 169.460547 .

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 15 / 20 / 19
[173.992899 173.992899 170.1429   ... 172.001827 172.001827 172.214412]
computing: 15 / 20 / 20
[ 8.889603  8.889603 11.51936  ...  9.964896  9.964896  9.982639]
computing: 15 / 20 / 21
[ 9.970587  9.970587 10.830654 ... 10.110382 10.110382 10.15404 ]
computing: 15 / 20 / 22
[ 89.829509  89.829509  90.464056 ... 139.928627 139.928627 142.526168]
computing: 15 / 20 / 23
[100.417595 100.417595 102.408578 ... 145.262366 145.262366 148.092618]
computing: 15 / 20 / 24
[20.777415 20.777415 14.815429 ... 15.419998 15.419998 15.351967]
computing: 15 / 20 / 25
[158.623224 158.623224 157.67172  ... 159.105974 159.105974 159.123524]
computing: 15 / 20 / 26
[0.       0.       0.017894 ... 0.251591 0.275613 0.308895]
computing: 15 / 20 / 27
[-0.       -0.        0.016435 ... -0.011828 -0.022022 -0.037747]
computing: 15 / 20 / 28
[-0.       -0.       -0.001469 ... -0.0644   -0.066209 -0.061404]
computing: 15 / 20 / 29
[ 0.        0.       -0.006922 ...  0.242922  0.266634  0.

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 16 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 16 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 16 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 16 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 16 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 16 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 16 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 16 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 16 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 16 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 16 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 16 / 18 / 71
[ 0.00e+00  0.00e+00  1.70e-05 ... -3.69e-04 -2.88e-04 -4.56e-04]
computing: 16 / 18 / 72
[0.00e+00 0.00e+00 8.00e-06 ... 4.23e-04 2.43e-04 1.43e-04]
computing: 16 / 18 / 73
[-0.00e+00 -0.00e+00 -1.10e-05 ... -3.14e-04 -2.72e-04 -3.04e-04]
computing: 16 / 18 / 74
[0.       0.       0.005893 ... 0.226351 0.262336 0.304988]
computing: 16 / 18 / 75
[-0.       -0.       -0.004911 ...  0.093732  0.153123  0.225012]
computing: 16 / 18 / 76
[ 0.        0.        0.000889 ... -0.044366 -0.06003  -0.070065]
computing: 16 / 18 / 77
[-0.       -0.        0.003132 ...  0.201198  0.204377  0.193592]
computing: 16 / 18 / 78
[0.       0.       0.00112  ... 0.028353 0.028404 0.028552]
computing: 16 / 18 / 79
[-0.       -0.        0.000934 ...  0.028136  0.028321  0.028334]
computing: 16 / 18 / 80
[-0.       -0.       -0.000169 ...  0.002671 -0.001309 -0.002696]
computing: 16 / 18 / 81
[ 0.        0.       -0.000596 ... -0.002272 -0.001718 -0.00227 ]
computing: 16 / 18 / 82
[0. 

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 17 / 0 / 18
[173.165021 173.165021 175.545826 ... 173.617258 173.617258 173.642272]
computing: 17 / 0 / 19
[175.786043 175.786043 175.811794 ... 175.694049 175.694049 175.716371]
computing: 17 / 0 / 20
[17.666418 17.666418 17.653417 ... 17.597218 17.597218 17.607634]
computing: 17 / 0 / 21
[14.296195 14.296195 15.212399 ... 14.247656 14.247656 14.218168]
computing: 17 / 0 / 22
[110.70678  110.70678  171.52414  ... 110.434674 110.434674 110.344449]
computing: 17 / 0 / 23
[105.451157 105.451157 166.171253 ... 104.961613 104.961613 104.852964]
computing: 17 / 0 / 24
[41.566953 41.566953 44.243274 ... 41.944791 41.944791 41.914727]
computing: 17 / 0 / 25
[167.26115  167.26115  159.787515 ... 167.158617 167.158617 167.087325]
computing: 17 / 0 / 26
[0.       0.       0.       ... 0.561018 0.557742 0.555186]
computing: 17 / 0 / 27
[ 0.        0.        0.       ... -0.009366 -0.036212 -0.062477]
computing: 17 / 0 / 28
[-0.       -0.       -0.       ...  0.491446  0.495759  0.50028

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 17 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 17 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 17 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 17 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 17 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 17 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 17 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 17 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 17 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 17 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 17 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 17 / 18 / 10
[388.572765 388.566703 388.608459 ... 385.583688 385.566843 385.562854]
computing: 17 / 18 / 11
[386.214669 386.202463 386.260627 ... 387.567371 387.602568 387.638763]
computing: 17 / 18 / 12
[291.854949 291.87402  291.92285  ... 296.592155 296.485124 296.3691  ]
computing: 17 / 18 / 13
[288.570845 288.571315 288.687927 ... 286.570603 286.560942 286.538014]
computing: 17 / 18 / 14
[147.649873 147.640602 147.725563 ... 150.409346 150.420289 150.441969]
computing: 17 / 18 / 15
[ 7.813312  7.813312 10.210543 ... 11.334835 11.341779 11.341779]
computing: 17 / 18 / 16
[17.210725 17.210725 20.269639 ... 18.372276 18.406812 18.406812]
computing: 17 / 18 / 17
[0.537529 0.537529 2.553801 ... 6.210732 6.241347 6.241347]
computing: 17 / 18 / 18
[170.838235 170.838235 169.460547 ... 168.583344 168.593067 168.593067]
computing: 17 / 18 / 19
[171.265262 171.265262 171.739618 ... 173.111803 173.205495 173.205495]
computing: 17 / 18 / 20
[10.156673 10.156673  9.782673 ...  8.85

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 18 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 18 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 18 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 18 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 18 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 18 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 18 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 18 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 18 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 18 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 18 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

C:\Users\loluc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\scipy\stats\_stats_py.py:9205: RuntimeWarning: invalid value encountered in scalar divide
  z = (s - expected) / np.sqrt(n1*n2*(n1+n2+1)/12.0)


computing: 19 / 1 / 4
[0.       0.       0.114331 ... 0.034603 0.052153 0.07333 ]
computing: 19 / 1 / 5
[0.       0.       0.051345 ... 0.075474 0.102897 0.136134]
computing: 19 / 1 / 6
[0.000e+00 0.000e+00 1.100e-05 ... 2.050e-03 3.274e-03 4.134e-03]
computing: 19 / 1 / 7
[0.000e+00 0.000e+00 6.000e-06 ... 1.239e-03 1.358e-03 1.487e-03]
computing: 19 / 1 / 8
[0.       0.       0.000137 ... 0.049399 0.046634 0.043339]
computing: 19 / 1 / 9
[429.484735 429.464587 429.457439 ... 418.545842 418.563528 418.566474]
computing: 19 / 1 / 10
[376.328855 376.34296  376.299998 ... 372.364844 372.388826 372.388132]
computing: 19 / 1 / 11
[373.166347 373.172705 373.177387 ... 371.608372 371.642433 371.648778]
computing: 19 / 1 / 12
[187.531256 187.683545 188.230672 ... 271.975799 271.972842 271.987583]
computing: 19 / 1 / 13
[191.391623 191.66875  192.133389 ... 263.189159 263.202054 263.258976]
computing: 19 / 1 / 14
[153.624315 153.590118 153.488329 ... 151.903326 151.903249 151.896671]
computing

cleaned_array = [s[3:-7] for s in timeseries]
resexcel=pd.DataFrame()
resexcel["name"] = cleaned_array
# calcolo per ogni valore di threshold di fpremover e saranno le mie colonne
thre=[2,4,6,8,10,14,18,25]
cps_thre=[]
for t in thre:
    print(f'threshold:{t}')
    new_cpsl=[]
    for i in range(len(timeseries)):
        df=dfl_st[i]
        gt=gtl[i]
        cps=np.array(cpsl_st[i],dtype="object")
        # FILTRO CPS
        new_cps=[]
        print("feature: ",end='')
        # per ogni feature, applico fpremover per ottenere nuovi cp con meno FP
        for idx,cp in enumerate(cps):
            
            print(f'{idx} ',end='')
            new_cp=FPremoverDTW(df.iloc[:,idx].values,cp,t)
            new_cps.append(new_cp)

        new_cpsl.append(new_cps)

    cps_thre.append(new_cpsl)

for idx,cpslt in enumerate(cps_thre):
    # per ogni riga, per ogni video, calcolo nuovi cp e calcolo lo score
    for div in range(1,4):
        f1_list_together=[]
        f1_list_comp4=[]
        print(f'div:{div}')
        for i in range(len(timeseries)):
            print(f"computing: {i}/{len(timeseries)}",end="\r")
            # prendo i dati standardizzati
            df=dfl_st[i]
            gt=gtl[i]
            cps=np.array(cpslt[i],dtype="object")
           
            #calcolare together
            f1_list_together.append(together(np.array(cps,dtype="object"),div))

            #calcolare comp4
            f1_list_comp4.append(Comp4(np.array(cps,dtype="object"),div,1))

        print(f"computing: {len(timeseries)}/{len(timeseries)}")
        resexcel[f"t:{idx} d:{div}"]=f1_list_together
resexcel.to_excel("outputFile/together&comp4_FPremoverDTW_before_standardized_thresholdStudy.xlsx")
    
        


cleaned_array = [s[3:-7] for s in timeseries]
resexcel=pd.DataFrame()
resexcel["name"] = cleaned_array
# calcolo per ogni valore di threshold di fpremover e saranno le mie colonne
thre=[0.2,0.4,0.8,1.0,1.4,1.8,2.5,3.0]
cps_thre=[]
for t in thre:
    print(f'threshold:{t}')
    new_cpsl=[]
    for i in range(len(timeseries)):
        df=dfl_no[i]
        gt=gtl[i]
        cps=np.array(cpsl_no[i],dtype="object")
        # FILTRO CPS
        new_cps=[]
        print("feature: ",end='')
        # per ogni feature, applico fpremover per ottenere nuovi cp con meno FP
        for idx,cp in enumerate(cps):
            
            print(f'{idx} ',end='')
            new_cp=FPremoverDTW(df.iloc[:,idx].values,cp,t)
            new_cps.append(new_cp)
        new_cpsl.append(new_cps)
    cps_thre.append(new_cpsl)


for idx,cpslt in enumerate(cps_thre):
    # per ogni riga, per ogni video, calcolo nuovi cp e calcolo lo score
    for div in range(1,4):
        f1_list_together=[]
        f1_list_comp4=[]
        print(f'div:{div}')
        for i in range(len(timeseries)):
            print(f"computing: {i}/{len(timeseries)}",end="\r")
            # prendo i dati standardizzati
            df=dfl_st[i]
            gt=gtl[i]
            cps=np.array(cpslt[i],dtype="object")

            #calcolare together
            f1_list_together.append(together(np.array(cps,dtype="object"),div))

            #calcolare comp4
            f1_list_comp4.append(Comp4(np.array(cps,dtype="object"),div,1))

        print(f"computing: {len(timeseries)}/{len(timeseries)}")
        resexcel[f"t:{idx} d:{div}"]=f1_list_together
resexcel.to_excel("outputFile/together&comp4_FPremoverDTW_before_normalized_thresholdStudy.xlsx")